### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by AkshithaReddy1899** [jaflih/Portfolio#8]
I have no complaints, your code is readable and has impressive use of comments

**Comment by mrparkersson** [comment]
Good job done so far too from me
 I think that is all to be done.

**Comment by Theodore354** [comment]
Code looks clean .

**Comment by jaflih** [comment]
@AkshithaReddy1899 @mrparkersson  @Theodore354 
![icegif-1433](https://user-images.githubusercontent.com/7243132/151622130-143815e2-9274-4781-b3ff-15c4a5ca94de.gif)
